version: 2

registries:
  github-packages-npm:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{ secrets.GITHUB_TOKEN }}

updates:
  - package-ecosystem: npm
    directory: "/backend"
    open-pull-requests-limit: 10
    registries:
      - github-packages-npm
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: "/frontend"
    open-pull-requests-limit: 10
    registries:
      - github-packages-npm
    schedule:
      interval: weekly
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 5
    schedule:
      interval: "weekly"
