version: "3.8"

volumes:
  frontend_node_modules:
  backend_node_modules:

services:
  frontend:
    container_name: frontend
    build:
      dockerfile: ./frontend/dockerfiles/Dockerfile.frontend
      context: .
    ports:
      - "3000:3000"
    volumes:
      - frontend_node_modules:/app/node_modules
      - ./frontend:/app
    environment:
      - NODE_ENV=production
    restart: on-failure

  backend:
    container_name: backend
    build:
      dockerfile: ./backend/dockerfiles/Dockerfile.backend
      context: .
    ports:
      - "5000:5000"
    volumes:
      - backend_node_modules:/app/node_modules
      - ./backend:/app
    environment:
      - NODE_ENV=production
      - PORT=5000
    restart: on-failure
