version: "3.8"
volumes:
  backend_node_modules:
  frontend_node_modules:
  db_data:

services:
  ####################### Backend  #######################
  backend:
    container_name: backend
    build:
      dockerfile: ./dockerfiles/Dockerfile.backend
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - backend_node_modules:/app/node_modules
      - ./backend:/app
    environment:
      NODE_ENV: production
      LOG_LEVEL: debug
      PORT: 5000
      MONGO_URL: mongodb://db:27017/flag-secops-hub
      DB_NAME: flag-secops-hub
      CORS_ORIGIN: http://localhost:3000
      JWT_SECRET: er123lan_gbtech$%&*()_+
      COOKIE_SECRET: lu123cio_gbtech$%&*()_+
    restart: on-failure
    depends_on:
      - database
  ####################### Frontend #######################
  frontend:
    container_name: frontend
    build:
      dockerfile: ./dockerfiles/Dockerfile.frontend
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - frontend_node_modules:/app/node_modules
      - ./frontend:/app
    environment:
      NODE_ENV: production
    restart: on-failure
  ####################### Database #######################
  database:
    image: mongo:6.0
    container_name: database
    ports:
      - 27017:27017
    volumes:
      - db_data:/data/db
    restart: on-failure
    healthcheck:
      test: ["CMD", "mongo", "--eval", '''db.runCommand("ping").ok''']
      interval: 30s
      timeout: 10s
      retries: 3
